### ISSUE TITLE
Add a shoov monitor.

### ISSUE THREAD

**Issue by mldk-tech** [UNFPAHQ/unfpa-global-shoov#2]

**Comment by mldk-tech** [comment]
Hi - I get a error message : Couldn't connect to selenium server.
https://app.shoov.io/#/repos/21611
Can you please check why?

**Comment by amitaibu** [comment]
Possibly because your `.shoov.yml` is missing the needed [add-on](https://github.com/amitaibu/shoov-behat/blob/master/.shoov.yml#L1-L2)

**Comment by mldk-tech** [comment]
In my .shoov.yml I added visual monitor tests. and I do not have this line in my other projects, are you sure?
